version: '3'

services:
  bot:
    build: ./
    restart: always
    ports:
      - '443:443'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: