"""many-to-many to many-to-one in media

Revision ID: 013dccba6cca
Revises: 3689ab16e6d7
Create Date: 2023-10-30 22:00:09.928181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013dccba6cca'
down_revision: Union[str, None] = '3689ab16e6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_publications')
    op.add_column('media', sa.Column('publication', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'publications', ['publication'], ['id'])
    op.add_column('publications', sa.Column('course_id', sa.Integer(), nullable=True))
    op.drop_constraint('publications_course_fkey', 'publications', type_='foreignkey')
    op.create_foreign_key(None, 'publications', 'courses', ['course_id'], ['id'])
    op.drop_column('publications', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.create_foreign_key('publications_course_fkey', 'publications', 'courses', ['course'], ['id'])
    op.drop_column('publications', 'course_id')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'publication')
    op.create_table('media_publications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='media_publications_media_id_fkey'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name='media_publications_publication_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_publications_pkey'),
    sa.UniqueConstraint('id', name='media_publications_id_key')
    )
    # ### end Alembic commands ###
