"""adding submissions

Revision ID: 1e86f594edd1
Revises: 6ebca9a68a92
Create Date: 2023-11-10 01:15:27.245485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e86f594edd1'
down_revision: Union[str, None] = '6ebca9a68a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('publication', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['student'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('media', sa.Column('submission', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'submissions', ['submission'], ['id'])
    op.add_column('publications', sa.Column('max_grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'max_grade')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'submission')
    op.drop_table('submissions')
    # ### end Alembic commands ###
