"""publication refactor

Revision ID: 33d789753406
Revises: d4ef7cf989a2
Create Date: 2023-10-26 18:08:52.182181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d789753406'
down_revision: Union[str, None] = 'd4ef7cf989a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('publications', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('publications', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
