"""media refactor

Revision ID: 3689ab16e6d7
Revises: 33d789753406
Create Date: 2023-10-27 22:02:14.544798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3689ab16e6d7'
down_revision: Union[str, None] = '33d789753406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'file_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=120),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('media', 'media_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'media_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('media', 'file_id',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
