"""add key to course

Revision ID: 621fa28379e9
Revises: a057b74f840e
Create Date: 2023-10-18 16:20:40.644284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621fa28379e9'
down_revision: Union[str, None] = 'a057b74f840e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('key', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'courses_students', ['id'])
    op.create_unique_constraint(None, 'media_publications', ['id'])
    op.create_unique_constraint(None, 'publications', ['id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'publications', type_='unique')
    op.drop_constraint(None, 'media_publications', type_='unique')
    op.drop_constraint(None, 'courses_students', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'key')
    # ### end Alembic commands ###
