"""initial

Revision ID: a057b74f840e
Revises: 
Create Date: 2023-10-12 15:21:16.259512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a057b74f840e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=64), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id', 'file_id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('courses_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_courses_students_student_id'), 'courses_students', ['student_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('media_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_courses_students_student_id'), table_name='courses_students')
    op.drop_table('courses_students')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('media')
    # ### end Alembic commands ###
